import { useCallback, useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router-dom';
import api from '../services/api';
import { useSetMobileHeader } from '../context/MobileHeaderContext';

const money = (value, currency = 'EUR') => new Intl.NumberFormat('es-ES', { style: 'currency', currency }).format(Number(value) || 0);
function Stat({ label, value, emphasis }) { return <div className={`rounded-2xl p-4 border ${emphasis ? 'bg-violet-600 border-violet-600 text-white' : 'bg-white border-gray-200'}`}><p className={`text-xs font-semibold ${emphasis ? 'text-violet-100' : 'text-gray-500'}`}>{label}</p><p className="text-xl font-bold mt-1">{value}</p></div>; }

export default function Performance() {
  useSetMobileHeader({ title: 'Rendimiento', actions: null });
  const navigate = useNavigate(); const [month, setMonth] = useState(() => new Date().toISOString().slice(0, 7)); const [data, setData] = useState(null); const [balances, setBalances] = useState([]); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [performance, balanceResult] = await Promise.all([api.get(`/staff/performance?month=${month}`), api.get('/staff/balances')]); setData(performance.data); setBalances(balanceResult.data?.balances || []); } catch (err) { setError(err.response?.data?.message || 'No se pudo cargar el rendimiento'); } finally { setLoading(false); } }, [month]);
  useEffect(() => { load(); }, [load]);
  const paymentTotals = useMemo(() => balances.reduce((acc, row) => ({ pending: acc.pending + Math.max(0, row.balance || 0), paid: acc.paid + (row.totalPaid || 0) }), { pending: 0, paid: 0 }), [balances]);
  const monthLabel = new Date(`${month}-01T12:00:00`).toLocaleDateString('es-ES', { month: 'long', year: 'numeric' });
  return <div className="space-y-5 max-w-5xl mx-auto"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-3"><div><h1 className="text-xl font-bold text-gray-900">Rendimiento</h1><p className="text-sm text-gray-500 mt-0.5">Facturación, salarios y margen del equipo</p></div><div className="flex gap-2"><input aria-label="Mes" type="month" value={month} onChange={(e) => setMonth(e.target.value)} className="min-h-11 border border-gray-300 bg-white rounded-xl px-3 text-sm" /><button onClick={() => navigate('/planificacion')} className="min-h-11 px-3 rounded-xl border border-gray-200 bg-white text-sm font-semibold text-gray-700">Planificación</button></div></div>
    {error && <div className="text-sm text-red-700 bg-red-50 border border-red-200 rounded-xl px-4 py-3">{error}</div>}
    {loading ? <div className="grid grid-cols-2 lg:grid-cols-3 gap-3">{Array.from({ length: 6 }).map((_, i) => <div key={i} className="h-24 rounded-2xl bg-gray-100 animate-pulse" />)}</div> : <><section><p className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">{monthLabel}</p><div className="grid grid-cols-2 lg:grid-cols-3 gap-3"><Stat label="Facturación del equipo" value={money(data?.totals?.generated)} emphasis /><Stat label="Coste del equipo" value={money(data?.totals?.cost)} /><Stat label="Margen para el negocio" value={money(data?.totals?.margin)} /><Stat label="Citas" value={data?.totals?.appointments || 0} /><Stat label="Pendiente de pagar" value={money(paymentTotals.pending)} /><Stat label="Pagado" value={money(paymentTotals.paid)} /></div><p className="text-xs text-gray-400 mt-2">El coste es estimado según la remuneración y los turnos registrados. La facturación solo incluye reservas con un servicio y precio guardados.</p></section>
      <section><h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2">Profesionales</h2><div className="bg-white border border-gray-200 rounded-2xl overflow-hidden shadow-sm divide-y divide-gray-100">{(data?.rows || []).length === 0 ? <p className="p-8 text-sm text-center text-gray-400">No hay profesionales</p> : data.rows.map((row) => <button key={row.employeeId} onClick={() => navigate(`/equipo/${row.employeeId}?tab=remuneracion`, { state: { from: '/rendimiento' } })} className="w-full p-4 flex items-center gap-3 text-left hover:bg-gray-50 min-h-[76px]"><div className="w-10 h-10 rounded-full text-white font-bold flex items-center justify-center shrink-0" style={{ backgroundColor: row.color || '#7C3AED' }}>{row.employeeName?.[0] || '?'}</div><div className="flex-1 min-w-0"><p className="text-sm font-semibold text-gray-900 truncate">{row.employeeName}</p><p className="text-xs text-gray-500 mt-0.5">{row.appointments} citas · {money(row.generated)} generado</p><p className="text-xs text-gray-400 mt-0.5">{money(row.cost)} coste · {money(row.margin)} margen</p></div><span className="text-gray-300">›</span></button>)}</div></section></>}
  </div>;
}
