import { useCallback, useEffect, useMemo, useState } from 'react';
import { useLocation, useNavigate, useParams, useSearchParams } from 'react-router-dom';
import api from '../services/api';
import Modal from '../components/Modal';
import { useAuth } from '../context/AuthContext';
import { useSetMobileHeader } from '../context/MobileHeaderContext';

const ROLE_LABELS = { owner: 'Propietario', manager: 'Encargado', staff: 'Personal' };
const ROLE_HELP = {
  owner: ['Acceso total al negocio', 'Gestiona equipo, roles y facturación'],
  manager: ['Gestiona la operativa', 'Accede a las funciones permitidas por el negocio'],
  staff: ['Ve la agenda', 'Gestiona sus citas', 'Realiza operaciones básicas'],
};
const DAYS = [['mon', 'Lunes'], ['tue', 'Martes'], ['wed', 'Miércoles'], ['thu', 'Jueves'], ['fri', 'Viernes'], ['sat', 'Sábado'], ['sun', 'Domingo']];
const inputCls = 'w-full min-h-11 border border-gray-300 rounded-xl px-3.5 py-2.5 text-sm bg-white focus:outline-none focus:ring-2 focus:ring-violet-500';
const money = (value, currency = 'EUR') => new Intl.NumberFormat('es-ES', { style: 'currency', currency }).format(Number(value) || 0);
const fullName = (p) => `${p?.firstName || ''} ${p?.lastName || ''}`.trim();

function Avatar({ professional, large = false }) {
  return <div className={`${large ? 'w-14 h-14 text-xl' : 'w-11 h-11 text-base'} rounded-full text-white font-bold flex items-center justify-center shrink-0`} style={{ backgroundColor: professional?.color || '#7C3AED' }}>{fullName(professional)[0]?.toUpperCase() || '?'}</div>;
}
function Loading() { return <div className="space-y-3"><div className="h-20 rounded-2xl bg-gray-100 animate-pulse" /><div className="h-36 rounded-2xl bg-gray-100 animate-pulse" /></div>; }
function Empty({ onCreate }) { return <div className="bg-white border border-gray-200 rounded-2xl p-10 text-center shadow-sm"><div className="w-12 h-12 mx-auto mb-3 rounded-full bg-violet-50 text-violet-600 flex items-center justify-center text-2xl">+</div><h2 className="font-semibold text-gray-900">Añade tu primer profesional</h2><p className="text-sm text-gray-500 mt-1 mb-5">Podrá recibir reservas aunque no tenga acceso a Vetra.</p><button onClick={onCreate} className="min-h-11 px-4 rounded-xl bg-violet-600 text-white text-sm font-semibold">Crear profesional</button></div>; }

function ProfessionalForm({ professional, onClose, onSaved }) {
  const { hasRole } = useAuth();
  const [form, setForm] = useState({ firstName: professional?.firstName || '', lastName: professional?.lastName || '', color: professional?.color || '#7C3AED' });
  const [access, setAccess] = useState({ enabled: false, email: '', role: 'staff' });
  const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  const submit = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { const res = professional?._id ? await api.put(`/staff/employees/${professional._id}`, form) : await api.post('/staff/employees', form); if (!professional && access.enabled) await api.post('/invitations', { name: `${form.firstName} ${form.lastName}`.trim(), email: access.email, role: access.role, professionalId: res.data._id }); onSaved(res.data); } catch (err) { setError(err.response?.data?.message || 'No se pudo guardar el profesional'); } finally { setSaving(false); } };
  return <Modal title={professional ? 'Editar profesional' : 'Nuevo profesional'} onClose={onClose}><form onSubmit={submit} className="space-y-4">
    {error && <p className="text-sm text-red-700 bg-red-50 rounded-xl px-3 py-2">{error}</p>}
    <div className="grid grid-cols-1 sm:grid-cols-2 gap-3"><label className="text-sm font-medium text-gray-700">Nombre<input autoFocus required value={form.firstName} onChange={(e) => setForm({ ...form, firstName: e.target.value })} className={`${inputCls} mt-1.5`} /></label><label className="text-sm font-medium text-gray-700">Apellidos<input value={form.lastName} onChange={(e) => setForm({ ...form, lastName: e.target.value })} className={`${inputCls} mt-1.5`} /></label></div>
    <label className="block text-sm font-medium text-gray-700">Color del avatar<div className="mt-1.5 flex items-center gap-3"><input type="color" value={form.color} onChange={(e) => setForm({ ...form, color: e.target.value })} className="w-12 h-11 rounded-xl border border-gray-300 p-1 bg-white" /><span className="text-sm text-gray-500">Identifica su agenda rápidamente</span></div></label>
    {!professional && <div className="border border-gray-200 rounded-xl p-3"><label className="min-h-11 flex items-center gap-3 text-sm font-semibold text-gray-800"><input type="checkbox" checked={access.enabled} onChange={(e) => setAccess({ ...access, enabled: e.target.checked })} className="w-5 h-5 accent-violet-600" />Dar acceso a Vetra</label><p className="text-xs text-gray-500 ml-8">Podrá iniciar sesión y gestionar las funciones permitidas por su rol.</p>{access.enabled && <div className="grid sm:grid-cols-2 gap-3 mt-3"><input required type="email" placeholder="email@ejemplo.com" value={access.email} onChange={(e) => setAccess({ ...access, email: e.target.value })} className={inputCls} /><select value={access.role} onChange={(e) => setAccess({ ...access, role: e.target.value })} className={inputCls}><option value="staff">Personal</option><option value="manager">Encargado</option>{hasRole('owner') && <option value="owner">Propietario</option>}</select></div>}</div>}
    <div className="flex justify-end gap-2 pt-2"><button type="button" onClick={onClose} className="min-h-11 px-4 rounded-xl text-sm font-semibold text-gray-600 bg-gray-100">Cancelar</button><button disabled={saving} className="min-h-11 px-4 rounded-xl text-sm font-semibold text-white bg-violet-600 disabled:opacity-50">{saving ? 'Guardando…' : 'Guardar'}</button></div>
  </form></Modal>;
}

function TeamList({ professionals, members, onCreate }) {
  const navigate = useNavigate();
  const linkedMemberIds = new Set(professionals.map((p) => p.member?._id).filter(Boolean).map(String));
  const unlinked = members.filter((m) => !linkedMemberIds.has(String(m._id)));
  return <div className="space-y-5 max-w-4xl mx-auto"><div className="flex items-start justify-between gap-3"><div><h1 className="text-xl font-bold text-gray-900">Equipo</h1><p className="text-sm text-gray-500 mt-0.5">{professionals.length} {professionals.length === 1 ? 'profesional' : 'profesionales'}</p></div><button onClick={onCreate} className="min-h-11 shrink-0 px-4 rounded-xl bg-violet-600 hover:bg-violet-700 text-white text-sm font-semibold shadow-sm">+ Profesional</button></div>
    {professionals.length === 0 ? <Empty onCreate={onCreate} /> : <div className="bg-white border border-gray-200 rounded-2xl overflow-hidden shadow-sm divide-y divide-gray-100">{professionals.map((p) => { const services = (p.services || []).filter((s) => s.active !== false).map((s) => s.name); return <button key={p._id} onClick={() => navigate(`/equipo/${p._id}`, { state: { from: '/equipo' } })} className="w-full min-h-[76px] p-4 flex items-center gap-3 text-left hover:bg-gray-50 transition-colors"><Avatar professional={p} /><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><p className="font-semibold text-gray-900 truncate">{fullName(p)}</p>{p.status !== 'active' && <span className="text-[11px] rounded-full px-2 py-0.5 bg-gray-100 text-gray-500">Inactivo</span>}</div><p className="text-xs text-gray-500 truncate mt-0.5">{services.length ? services.join(', ') : 'Sin servicios asignados'}</p><p className="text-xs text-gray-400 mt-0.5">{p.scheduleMode === 'custom' ? 'Horario propio' : 'Horario del negocio'}</p></div><span className={`hidden sm:inline-flex text-[11px] font-semibold px-2.5 py-1 rounded-full ${p.member ? 'bg-emerald-50 text-emerald-700' : p.pendingInvitation ? 'bg-amber-50 text-amber-700' : 'bg-gray-100 text-gray-500'}`}>{p.member ? 'Con acceso' : p.pendingInvitation ? 'Invitación pendiente' : 'Sin acceso'}</span><span className="text-gray-300">›</span></button>; })}</div>}
    {unlinked.length > 0 && <section><h2 className="text-xs font-semibold text-gray-400 uppercase tracking-wide mb-2 px-1">Usuarios sin profesional</h2><div className="bg-white border border-gray-200 rounded-2xl divide-y divide-gray-100">{unlinked.map((m) => <div key={m._id} className="px-4 py-3 flex items-center justify-between gap-3"><div className="min-w-0"><p className="text-sm font-semibold text-gray-800 truncate">{m.userName || m.userEmail}</p><p className="text-xs text-gray-400 truncate">{m.userEmail}</p></div><span className="text-xs text-gray-500">{ROLE_LABELS[m.role] || m.role}</span></div>)}</div></section>}
  </div>;
}

function GeneralTab({ professional, performance, onEdit, onSave }) {
  const navigate = useNavigate(); const [editingSchedule, setEditingSchedule] = useState(false); const [scheduleMode, setScheduleMode] = useState(professional.scheduleMode || 'business'); const [weekly, setWeekly] = useState(professional.weeklySchedule || {}); const [vacations, setVacations] = useState(professional.vacations || []); const [vacationForm, setVacationForm] = useState({ startDate: '', endDate: '', reason: '' });
  const toggleDay = (key) => setWeekly((w) => ({ ...w, [key]: w[key]?.enabled ? { ...w[key], enabled: false } : { enabled: true, start: w[key]?.start || '09:00', end: w[key]?.end || '18:00' } }));
  const save = async () => { await onSave({ scheduleMode, weeklySchedule: weekly, vacations }); setEditingSchedule(false); };
  const futureVacations = (professional.vacations || []).filter((v) => v.endDate >= new Date().toISOString().slice(0, 10));
  return <div className="space-y-4"><section className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm flex items-center gap-3"><Avatar professional={professional} large /><div className="flex-1 min-w-0"><h2 className="text-lg font-bold text-gray-900 truncate">{fullName(professional)}</h2><span className={`text-xs font-semibold ${professional.status === 'active' ? 'text-emerald-600' : 'text-gray-400'}`}>● {professional.status === 'active' ? 'Activo' : 'Inactivo'}</span></div><button onClick={onEdit} className="min-h-11 px-3 text-sm font-semibold text-violet-700 rounded-xl hover:bg-violet-50">Editar</button></section>
    <section className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm"><div className="flex justify-between items-start gap-3"><div><p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Horario</p><p className="text-sm font-semibold text-gray-900 mt-1">{professional.scheduleMode === 'custom' ? 'Tiene horario propio' : 'Sigue el horario del negocio'}</p></div><button onClick={() => setEditingSchedule(!editingSchedule)} className="min-h-11 px-3 text-sm font-semibold text-violet-700 rounded-xl hover:bg-violet-50">{editingSchedule ? 'Cerrar' : 'Editar'}</button></div>
      {editingSchedule && <div className="mt-4 pt-4 border-t border-gray-100 space-y-3"><div className="grid grid-cols-1 sm:grid-cols-2 gap-2">{[['business', 'Horario del negocio'], ['custom', 'Horario propio y vacaciones']].map(([value, label]) => <button key={value} onClick={() => setScheduleMode(value)} className={`min-h-11 rounded-xl border px-3 text-sm font-semibold ${scheduleMode === value ? 'border-violet-500 bg-violet-50 text-violet-700' : 'border-gray-200 text-gray-600'}`}>{label}</button>)}</div>{scheduleMode === 'custom' && <><div className="space-y-2">{DAYS.map(([key, label]) => { const day = weekly[key] || {}; return <div key={key} className="min-h-11 flex items-center gap-2"><label className="flex items-center gap-2 w-28 text-sm font-medium"><input type="checkbox" checked={!!day.enabled} onChange={() => toggleDay(key)} />{label}</label>{day.enabled && <><input type="time" value={day.start || '09:00'} onChange={(e) => setWeekly({ ...weekly, [key]: { ...day, start: e.target.value } })} className="border rounded-lg px-2 py-2 text-sm min-w-0" /><span className="text-gray-400">–</span><input type="time" value={day.end || '18:00'} onChange={(e) => setWeekly({ ...weekly, [key]: { ...day, end: e.target.value } })} className="border rounded-lg px-2 py-2 text-sm min-w-0" /></>}</div>; })}</div><div className="pt-3 border-t border-gray-100"><p className="text-sm font-semibold text-gray-800 mb-2">Vacaciones</p>{vacations.map((v, i) => <div key={`${v.startDate}-${i}`} className="flex items-center gap-2 py-1 text-sm"><span className="flex-1">{v.startDate} – {v.endDate}{v.reason ? ` · ${v.reason}` : ''}</span><button onClick={() => setVacations(vacations.filter((_, idx) => idx !== i))} className="w-11 h-11 text-red-500" aria-label="Eliminar vacaciones">×</button></div>)}<div className="grid sm:grid-cols-3 gap-2"><input type="date" value={vacationForm.startDate} onChange={(e) => setVacationForm({ ...vacationForm, startDate: e.target.value })} className={inputCls} /><input type="date" min={vacationForm.startDate} value={vacationForm.endDate} onChange={(e) => setVacationForm({ ...vacationForm, endDate: e.target.value })} className={inputCls} /><button disabled={!vacationForm.startDate || !vacationForm.endDate} onClick={() => { setVacations([...vacations, vacationForm]); setVacationForm({ startDate: '', endDate: '', reason: '' }); }} className="min-h-11 rounded-xl border border-gray-200 text-sm font-semibold disabled:opacity-40">Añadir vacaciones</button></div></div></>}<button onClick={save} className="min-h-11 w-full sm:w-auto px-4 rounded-xl bg-violet-600 text-white text-sm font-semibold">Guardar horario</button></div>}
    </section><section className="grid sm:grid-cols-2 gap-4"><div className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm"><p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Agenda</p><p className="text-sm text-gray-900 mt-2"><b>{performance?.appointments || 0} citas</b> este mes · {money(performance?.generated || 0)}</p><button onClick={() => navigate(`/reservations?professional=${professional._id}`)} className="min-h-11 mt-2 text-sm font-semibold text-violet-700">Ver agenda →</button></div><div className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm"><p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Próximas vacaciones</p><p className="text-sm text-gray-900 mt-2">{futureVacations.length ? `${futureVacations[0].startDate} – ${futureVacations[0].endDate}` : 'Ninguna'}</p><p className="text-xs text-gray-400 mt-2">Las vacaciones propias se guardan en su ficha.</p></div></section>
  </div>;
}

function ServicesTab({ professional, onSave }) {
  const [services, setServices] = useState(professional.services || []); const [saving, setSaving] = useState(false);
  const update = (i, patch) => setServices(services.map((s, idx) => idx === i ? { ...s, ...patch } : s));
  const save = async () => { setSaving(true); await onSave({ services: services.filter((s) => s.name.trim()).map((s) => ({ ...s, name: s.name.trim() })) }); setSaving(false); };
  return <section className="bg-white border border-gray-200 rounded-2xl shadow-sm overflow-hidden"><div className="p-4 border-b border-gray-100"><h2 className="font-semibold text-gray-900">Servicios de {professional.firstName}</h2><p className="text-sm text-gray-500 mt-1">Añade los servicios que realiza. Solo se le podrá reservar para estos servicios.</p></div><div className="p-4 space-y-3">{services.length === 0 && <p className="text-sm text-gray-400 text-center py-5">Todavía no tiene servicios asignados</p>}{services.map((service, i) => <div key={service._id || i} className="border border-gray-200 rounded-xl p-3"><div className="flex gap-2"><input aria-label="Servicio" placeholder="Ej. Manicura" value={service.name} onChange={(e) => update(i, { name: e.target.value })} className={`${inputCls} flex-1`} /><button onClick={() => setServices(services.filter((_, idx) => idx !== i))} className="w-11 h-11 rounded-xl text-red-500 hover:bg-red-50" aria-label="Eliminar servicio">×</button></div><div className="grid grid-cols-2 gap-2 mt-2"><label className="text-xs text-gray-500">Duración (min)<input type="number" min="5" step="5" value={service.duration} onChange={(e) => update(i, { duration: Number(e.target.value) })} className={`${inputCls} mt-1`} /></label><label className="text-xs text-gray-500">Precio (€)<input type="number" min="0" step="0.01" value={service.price} onChange={(e) => update(i, { price: Number(e.target.value) })} className={`${inputCls} mt-1`} /></label></div></div>)}<div className="flex flex-col sm:flex-row gap-2"><button onClick={() => setServices([...services, { name: '', duration: 30, price: 0, active: true }])} className="min-h-11 px-4 rounded-xl border border-gray-200 text-sm font-semibold text-gray-700">+ Añadir servicio</button><button disabled={saving} onClick={save} className="min-h-11 px-4 rounded-xl bg-violet-600 text-white text-sm font-semibold sm:ml-auto disabled:opacity-50">{saving ? 'Guardando…' : 'Guardar servicios'}</button></div></div></section>;
}

function Metric({ label, value, note }) { return <div className="bg-gray-50 rounded-xl p-3"><p className="text-xs text-gray-500">{label}</p><p className="text-lg font-bold text-gray-900 mt-1">{value}</p>{note && <p className="text-[11px] text-gray-400 mt-0.5">{note}</p>}</div>; }
function CompensationTab({ professional, performance, onRefresh }) {
  const comp = professional.activeCompensation; const [editing, setEditing] = useState(!comp); const [form, setForm] = useState({ paymentType: comp?.paymentType || 'monthly_fixed', baseAmount: comp?.baseAmount || '', effectiveFrom: new Date().toISOString().slice(0, 10), currency: 'EUR' }); const [saving, setSaving] = useState(false);
  const submit = async (e) => { e.preventDefault(); setSaving(true); await api.post(`/staff/employees/${professional._id}/compensations`, { ...form, baseAmount: Number(form.baseAmount) }); await onRefresh(); setEditing(false); setSaving(false); };
  const compText = comp ? `${money(comp.baseAmount, comp.currency)} ${comp.paymentType === 'monthly_fixed' ? '/mes' : comp.paymentType === 'hourly' ? '/hora' : '/turno'}` : '';
  return <div className="space-y-4"><section className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm"><div className="flex justify-between gap-3"><div><p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">Cómo cobra</p>{comp ? <><p className="font-semibold text-gray-900 mt-2">{comp.paymentType === 'monthly_fixed' ? 'Sueldo fijo' : comp.paymentType === 'hourly' ? 'Por horas' : 'Por turno'}</p><p className="text-sm text-gray-500">{compText}</p></> : <p className="text-sm text-gray-600 mt-2">Sin definir cómo cobra</p>}</div><button onClick={() => setEditing(!editing)} className="min-h-11 px-3 text-sm font-semibold text-violet-700">{comp ? 'Cambiar' : 'Configurar remuneración'}</button></div>{editing && <form onSubmit={submit} className="mt-4 pt-4 border-t border-gray-100 grid sm:grid-cols-3 gap-3"><select value={form.paymentType} onChange={(e) => setForm({ ...form, paymentType: e.target.value })} className={inputCls}><option value="monthly_fixed">Sueldo mensual</option><option value="hourly">Por hora</option><option value="per_shift">Por turno</option></select><input required type="number" min="0" step="0.01" placeholder="Importe" value={form.baseAmount} onChange={(e) => setForm({ ...form, baseAmount: e.target.value })} className={inputCls} /><button disabled={saving} className="min-h-11 rounded-xl bg-violet-600 text-white text-sm font-semibold">Guardar</button></form>}</section><section className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm"><p className="text-xs font-semibold text-gray-400 uppercase tracking-wide">{new Date().toLocaleDateString('es-ES', { month: 'long', year: 'numeric' })}</p><div className="grid grid-cols-2 gap-3 mt-3"><Metric label="Ingresos generados" value={money(performance?.generated)} /><Metric label="Citas" value={performance?.appointments || 0} /><Metric label="Coste estimado" value={money(performance?.cost)} note="Según turnos y remuneración" /><Metric label="Margen para el negocio" value={money(performance?.margin)} /></div></section></div>;
}

function AccessTab({ professional, onRefresh }) {
  const { hasRole } = useAuth(); const member = professional.member; const invite = professional.pendingInvitation; const [form, setForm] = useState({ email: professional.email || '', role: 'staff' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const inviteUser = async (e) => { e.preventDefault(); setSaving(true); setError(''); try { await api.post('/invitations', { name: fullName(professional), ...form, professionalId: professional._id }); await onRefresh(); } catch (err) { setError(err.response?.data?.message || 'No se pudo enviar la invitación'); } finally { setSaving(false); } };
  const changeRole = async (role) => { try { await api.put(`/members/${member._id}`, { role }); await onRefresh(); } catch (err) { setError(err.response?.data?.message || 'No se pudo cambiar el rol'); } };
  const revoke = async () => { if (!confirm(`¿Revocar el acceso de ${professional.firstName}? El profesional, sus reservas y configuración se conservarán.`)) return; try { await api.delete(`/staff/employees/${professional._id}/access`); await onRefresh(); } catch (err) { setError(err.response?.data?.message || 'No se pudo revocar el acceso'); } };
  return <section className="bg-white border border-gray-200 rounded-2xl p-4 shadow-sm"><h2 className="font-semibold text-gray-900">Acceso a Vetra</h2>{error && <p className="text-sm text-red-700 bg-red-50 rounded-xl px-3 py-2 mt-3">{error}</p>}{member ? <div className="mt-4"><p className="text-sm font-semibold text-emerald-700">✓ {professional.firstName} tiene acceso</p><p className="text-sm text-gray-500 mt-1">{member.userEmail}</p><label className="block text-xs font-semibold text-gray-500 mt-5">Rol<select value={member.role} disabled={!hasRole('owner') || member.role === 'owner'} onChange={(e) => changeRole(e.target.value)} className={`${inputCls} mt-1.5 max-w-sm disabled:bg-gray-50`}><option value="staff">Personal</option><option value="manager">Encargado</option><option value="owner">Propietario</option></select></label><ul className="mt-4 space-y-1">{ROLE_HELP[member.role]?.map((x) => <li key={x} className="text-sm text-gray-600">• {x}</li>)}</ul>{hasRole('owner') && member.role !== 'owner' && <button onClick={revoke} className="min-h-11 mt-5 px-3 rounded-xl text-sm font-semibold text-red-600 hover:bg-red-50">Revocar acceso</button>}</div> : invite ? <div className="mt-4"><p className="text-sm font-semibold text-amber-700">Invitación pendiente</p><p className="text-sm text-gray-500 mt-1">{invite.email} · {ROLE_LABELS[invite.role]}</p><p className="text-xs text-gray-400 mt-3">El acceso se vinculará automáticamente al aceptar la invitación.</p></div> : <div className="mt-4"><p className="text-sm text-gray-600">{professional.firstName} no tiene acceso a Vetra. Puede recibir citas igualmente.</p><form onSubmit={inviteUser} className="mt-5 space-y-3 max-w-md"><label className="block text-sm font-medium text-gray-700">Email<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} className={`${inputCls} mt-1.5`} /></label><label className="block text-sm font-medium text-gray-700">Rol<select value={form.role} onChange={(e) => setForm({ ...form, role: e.target.value })} className={`${inputCls} mt-1.5`}><option value="staff">Personal</option><option value="manager">Encargado</option>{hasRole('owner') && <option value="owner">Propietario</option>}</select></label><p className="text-xs text-gray-400">Podrá iniciar sesión y gestionar las funciones permitidas por su rol.</p><button disabled={saving} className="min-h-11 px-4 rounded-xl bg-violet-600 text-white text-sm font-semibold disabled:opacity-50">{saving ? 'Enviando…' : 'Invitar a Vetra'}</button></form></div>}</section>;
}

function ProfessionalDetail({ professionals, performance, onRefresh }) {
  const { id } = useParams(); const navigate = useNavigate(); const location = useLocation(); const [params, setParams] = useSearchParams(); const professional = professionals.find((p) => String(p._id) === id); const [edit, setEdit] = useState(false); const tabs = ['general', 'servicios', 'remuneracion', 'acceso']; const active = tabs.includes(params.get('tab')) ? params.get('tab') : 'general';
  if (!professional) return <div className="text-center py-16 text-gray-500">Profesional no encontrado</div>;
  const row = performance?.rows?.find((r) => String(r.employeeId) === id); const save = async (payload) => { await api.put(`/staff/employees/${id}`, payload); await onRefresh(); };
  return <div className="space-y-4 max-w-4xl mx-auto"><div className="flex items-center gap-3"><button onClick={() => navigate(location.state?.from || '/equipo')} className="w-11 h-11 rounded-xl hover:bg-gray-100 text-gray-600 text-xl" aria-label="Volver">‹</button><div className="min-w-0"><p className="text-xs text-gray-400">Equipo</p><h1 className="text-xl font-bold text-gray-900 truncate">{fullName(professional)}</h1></div></div><div className="overflow-x-auto [scrollbar-width:none] -mx-4 px-4"><div className="flex gap-1 bg-gray-100 p-1 rounded-xl min-w-max">{tabs.map((tab) => <button key={tab} onClick={() => setParams({ tab })} className={`min-h-11 px-4 rounded-lg text-sm font-semibold capitalize ${active === tab ? 'bg-white text-violet-700 shadow-sm' : 'text-gray-500'}`}>{tab === 'remuneracion' ? 'Remuneración' : tab}</button>)}</div></div>{active === 'general' && <GeneralTab professional={professional} performance={row} onEdit={() => setEdit(true)} onSave={save} />}{active === 'servicios' && <ServicesTab professional={professional} onSave={save} />}{active === 'remuneracion' && <CompensationTab professional={professional} performance={row} onRefresh={onRefresh} />}{active === 'acceso' && <AccessTab professional={professional} onRefresh={onRefresh} />}{edit && <ProfessionalForm professional={professional} onClose={() => setEdit(false)} onSaved={async () => { setEdit(false); await onRefresh(); }} />}</div>;
}

export default function Team() {
  const { id } = useParams(); const [professionals, setProfessionals] = useState([]); const [members, setMembers] = useState([]); const [performance, setPerformance] = useState(null); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [create, setCreate] = useState(false); const navigate = useNavigate(); const month = useMemo(() => new Date().toISOString().slice(0, 7), []);
  useSetMobileHeader({ title: 'Equipo', actions: null });
  const load = useCallback(async () => { try { setError(''); const [p, m, perf] = await Promise.all([api.get('/staff/employees?includeInactive=true'), api.get('/members'), api.get(`/staff/performance?month=${month}`)]); setProfessionals(p.data); setMembers(m.data); setPerformance(perf.data); } catch (err) { setError(err.response?.data?.message || 'No se pudo cargar el equipo'); } finally { setLoading(false); } }, [month]);
  useEffect(() => { load(); }, [load]); if (loading) return <Loading />;
  return <>{error && <div className="max-w-4xl mx-auto mb-4 text-sm text-red-700 bg-red-50 border border-red-200 rounded-xl px-4 py-3">{error}</div>}{id ? <ProfessionalDetail professionals={professionals} performance={performance} onRefresh={load} /> : <TeamList professionals={professionals} members={members} onCreate={() => setCreate(true)} />}{create && <ProfessionalForm onClose={() => setCreate(false)} onSaved={async (p) => { setCreate(false); await load(); navigate(`/equipo/${p._id}`); }} />}</>;
}
